### ISSUE TITLE
Links unavailable in http://dev.generals.io/replays

### ISSUE THREAD

**Issue by 0x0cqq** [vzhou842/generals.io-Replay-Simulator#1]
The link in http://dev.generals.io/replays is unavilable to download replays now.

**Comment by 0x0cqq** [comment]
This link to dropbox. 
![](https://i.loli.net/2019/06/08/5cfb3583ef5a567174.png)

**Comment by 0x0cqq** [comment]
@vzhou842

**Comment by vzhou842** [comment]
I'm not sure what happened to the dropbox. Unfortunately, I don't have those replays anymore - I sold the game and am no longer involved with it. However, I believe the replays are up on a public AWS bucket somewhere that you could download yourself - ask around, I think other bot developers have done this.
